"""Add fk constraint on series_id

Revision ID: 0ca0b0f9cb59
Revises: 9a8976c707f9
Create Date: 2025-05-29 22:03:49.847270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ca0b0f9cb59'
down_revision: Union[str, None] = '9a8976c707f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'games', 'series', ['series_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    # ### end Alembic commands ###
