"""Add additional_details column to game

Revision ID: 0d0b2d97958d
Revises: c3e303128e9a
Create Date: 2025-03-03 23:50:00.964635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d0b2d97958d'
down_revision: Union[str, None] = 'c3e303128e9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('additional_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'additional_details')
    # ### end Alembic commands ###
