"""source_data and remove external_ids from team

Revision ID: 0d7df9b7995e
Revises: 51f5defaf388
Create Date: 2025-07-03 13:49:01.338720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d7df9b7995e'
down_revision: Union[str, None] = '51f5defaf388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
            """
            UPDATE teams
            SET additional_details = jsonb_set(additional_details, '{external_ids}', external_ids)
            WHERE external_ids != '{}'::JSONB
            """
        )
    op.drop_column('teams', 'external_ids')
    op.alter_column('teams', 'additional_details', nullable=True, new_column_name='source_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('external_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('teams', 'source_data', nullable=True, new_column_name='additional_details')
    # ### end Alembic commands ###
