"""Removes unused game version

Revision ID: 14ae6988f658
Revises: c928c5a9af04
Create Date: 2024-07-13 01:24:22.871226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ae6988f658'
down_revision: Union[str, None] = 'c928c5a9af04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'game_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('game_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
