"""further process participant stat data fields

Revision ID: 190cf359d2a5
Revises: fc71cacb307e
Create Date: 2025-07-01 22:03:41.329804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '190cf359d2a5'
down_revision: Union[str, None] = 'fc71cacb307e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant_stats', sa.Column('total_damage_dealt', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('physical_damage_dealt', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('magic_damage_dealt', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('true_damage_dealt', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('total_damage_dealt_to_champions', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('physical_damage_dealt_to_champions', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('magic_damage_dealt_to_champions', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('true_damage_dealt_to_champions', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('total_damage_taken', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('physical_damage_taken', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('magic_damage_taken', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('true_damage_taken', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('damage_self_mitigated', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('total_damage_shielded_on_teammates', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('damage_dealt_to_buildings', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('damage_dealt_to_turrets', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('wards_placed', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('wards_killed', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('vision_score', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('total_heals_on_teammates', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('total_ally_jungle_minions_killed', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('total_enemy_jungle_minions_killed', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('champ_level', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('champ_experience', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('basic_pings', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('command_pings', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('danger_pings', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('get_back_pings', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('retreat_pings', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('on_my_way_pings', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('assist_me_pings', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('enemy_missing_pings', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('push_pings', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('all_in_pings', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('hold_pings', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('vision_cleared_pings', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('enemy_vision_pings', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('need_vision_pings', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('total_time_CC_dealt', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('time_CC_ing_others', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('current_gold', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('total_gold', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('perks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('participant_stats', sa.Column('position_x', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('position_y', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('alive', sa.Boolean(), nullable=True))
    op.add_column('participant_stats', sa.Column('respawn_time', sa.Integer(), nullable=True))
    op.add_column('participant_stats', sa.Column('game_time', sa.Integer(), nullable=True))
    op.drop_constraint('participant_stats_participant_id_key', 'participant_stats', type_='unique')
    op.create_index('idx_participant_stats_game_time', 'participant_stats', ['game_time'], unique=False)
    op.create_index('idx_participant_stats_participant_id', 'participant_stats', ['participant_id'], unique=False)
    op.create_index('idx_participant_stats_participant_time', 'participant_stats', ['participant_id', 'game_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_participant_stats_participant_time', table_name='participant_stats')
    op.drop_index('idx_participant_stats_participant_id', table_name='participant_stats')
    op.drop_index('idx_participant_stats_game_time', table_name='participant_stats')
    op.create_unique_constraint('participant_stats_participant_id_key', 'participant_stats', ['participant_id'])
    op.drop_column('participant_stats', 'game_time')
    op.drop_column('participant_stats', 'respawn_time')
    op.drop_column('participant_stats', 'alive')
    op.drop_column('participant_stats', 'position_y')
    op.drop_column('participant_stats', 'position_x')
    op.drop_column('participant_stats', 'perks')
    op.drop_column('participant_stats', 'total_gold')
    op.drop_column('participant_stats', 'current_gold')
    op.drop_column('participant_stats', 'time_CC_ing_others')
    op.drop_column('participant_stats', 'total_time_CC_dealt')
    op.drop_column('participant_stats', 'need_vision_pings')
    op.drop_column('participant_stats', 'enemy_vision_pings')
    op.drop_column('participant_stats', 'vision_cleared_pings')
    op.drop_column('participant_stats', 'hold_pings')
    op.drop_column('participant_stats', 'all_in_pings')
    op.drop_column('participant_stats', 'push_pings')
    op.drop_column('participant_stats', 'enemy_missing_pings')
    op.drop_column('participant_stats', 'assist_me_pings')
    op.drop_column('participant_stats', 'on_my_way_pings')
    op.drop_column('participant_stats', 'retreat_pings')
    op.drop_column('participant_stats', 'get_back_pings')
    op.drop_column('participant_stats', 'danger_pings')
    op.drop_column('participant_stats', 'command_pings')
    op.drop_column('participant_stats', 'basic_pings')
    op.drop_column('participant_stats', 'champ_experience')
    op.drop_column('participant_stats', 'champ_level')
    op.drop_column('participant_stats', 'total_enemy_jungle_minions_killed')
    op.drop_column('participant_stats', 'total_ally_jungle_minions_killed')
    op.drop_column('participant_stats', 'total_heals_on_teammates')
    op.drop_column('participant_stats', 'vision_score')
    op.drop_column('participant_stats', 'wards_killed')
    op.drop_column('participant_stats', 'wards_placed')
    op.drop_column('participant_stats', 'damage_dealt_to_turrets')
    op.drop_column('participant_stats', 'damage_dealt_to_buildings')
    op.drop_column('participant_stats', 'total_damage_shielded_on_teammates')
    op.drop_column('participant_stats', 'damage_self_mitigated')
    op.drop_column('participant_stats', 'true_damage_taken')
    op.drop_column('participant_stats', 'magic_damage_taken')
    op.drop_column('participant_stats', 'physical_damage_taken')
    op.drop_column('participant_stats', 'total_damage_taken')
    op.drop_column('participant_stats', 'true_damage_dealt_to_champions')
    op.drop_column('participant_stats', 'magic_damage_dealt_to_champions')
    op.drop_column('participant_stats', 'physical_damage_dealt_to_champions')
    op.drop_column('participant_stats', 'total_damage_dealt_to_champions')
    op.drop_column('participant_stats', 'true_damage_dealt')
    op.drop_column('participant_stats', 'magic_damage_dealt')
    op.drop_column('participant_stats', 'physical_damage_dealt')
    op.drop_column('participant_stats', 'total_damage_dealt')
    # ### end Alembic commands ###
