"""Remove participant stats moved into ParticipantStat

Revision ID: 1a7cdbcd4176
Revises: b63e2b25866f
Create Date: 2025-05-05 05:03:24.621558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a7cdbcd4176'
down_revision: Union[str, None] = 'b63e2b25866f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'champion_name')
    op.drop_column('participants', 'neutral_minions_killed')
    op.drop_column('participants', 'cspm')
    op.drop_column('participants', 'assists')
    op.drop_column('participants', 'missions')
    op.drop_column('participants', 'total_minions_killed')
    op.drop_column('participants', 'deaths')
    op.drop_column('participants', 'game_duration')
    op.drop_column('participants', 'win')
    op.drop_column('participants', 'total_cs')
    op.drop_column('participants', 'participant')
    op.drop_column('participants', 'challenges')
    op.drop_column('participants', 'kda')
    op.drop_column('participants', 'kills')
    op.drop_column('participants', 'perks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('perks', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('participants', sa.Column('kills', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('participants', sa.Column('kda', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('participants', sa.Column('challenges', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('participants', sa.Column('participant', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('participants', sa.Column('total_cs', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('participants', sa.Column('win', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('participants', sa.Column('game_duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('participants', sa.Column('deaths', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('participants', sa.Column('total_minions_killed', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('participants', sa.Column('missions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('participants', sa.Column('assists', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('participants', sa.Column('cspm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('participants', sa.Column('neutral_minions_killed', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('participants', sa.Column('champion_name', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
