"""Refactors tournament model

Revision ID: 2dd38761d245
Revises: e177d8916aec
Create Date: 2025-02-12 23:25:05.504595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2dd38761d245'
down_revision: Union[str, None] = 'e177d8916aec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('tournament_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('tournaments', 'shortened_name')
    op.drop_column('tournaments', 'grid_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('grid_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tournaments', sa.Column('shortened_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('tournaments', 'tournament_details')
    # ### end Alembic commands ###
