"""Updates Account typing

Revision ID: 32bf671416c3
Revises:
Create Date: 2024-07-27 22:38:01.298831

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "32bf671416c3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "accounts", "puuid", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "accounts", "last_update", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column("accounts", "player_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("accounts", "player_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "accounts", "last_update", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "accounts", "puuid", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###
