"""Add updated column to all tables and correctly set onupdate

Revision ID: 4490a7fa49d8
Revises: 5434c3d0adcd
Create Date: 2025-05-23 23:43:48.704606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from datetime import datetime

# revision identifiers, used by Alembic.
revision: str = '4490a7fa49d8'
down_revision: Union[str, None] = '5434c3d0adcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_dtos', sa.Column('updated', sa.DateTime(), nullable=False, server_default=str(datetime.now())))
    op.add_column('teams', sa.Column('updated', sa.DateTime(), nullable=False, server_default=str(datetime.now())))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'updated')
    op.drop_column('team_dtos', 'updated')
    # ### end Alembic commands ###
