"""remove external_ids from tournament

Revision ID: 51f5defaf388
Revises: 190cf359d2a5
Create Date: 2025-07-02 17:15:35.563812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51f5defaf388'
down_revision: Union[str, None] = '190cf359d2a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE tournaments
        SET source_data = jsonb_set(source_data, '{external_ids}', external_ids)
        WHERE external_ids != '{}'::JSONB
        """
    )
    op.drop_column('tournaments', 'external_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('external_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
