"""add event_type column to tournament table

Revision ID: 530452363d3e
Revises: 9f75c52e8471
Create Date: 2025-02-13 00:08:05.365482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '530452363d3e'
down_revision: Union[str, None] = '9f75c52e8471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('event_type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'event_type')
    # ### end Alembic commands ###
