"""Add fk_team_id field to team_dto

Revision ID: 5434c3d0adcd
Revises: c1a1d5ae388e
Create Date: 2025-05-18 14:26:08.043537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5434c3d0adcd'
down_revision: Union[str, None] = 'c1a1d5ae388e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_dtos', sa.Column('fk_team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'team_dtos', 'teams', ['fk_team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_dtos', type_='foreignkey')
    op.drop_column('team_dtos', 'fk_team_id')
    # ### end Alembic commands ###
