"""Refactors position association to allow for NULL positions

Revision ID: 56c95923a0d4
Revises: ba9e31392997
Create Date: 2024-10-04 18:47:30.754903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56c95923a0d4'
down_revision: Union[str, None] = 'ba9e31392997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_team_associations', 'position',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_team_associations', 'position',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###
