"""additional information rename

Revision ID: 5a4de713538e
Revises: b19e1e87a27b
Create Date: 2025-02-12 21:48:40.365379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a4de713538e'
down_revision: Union[str, None] = 'b19e1e87a27b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('additional_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('teams', 'additional_information')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('additional_information', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('teams', 'additional_details')
    # ### end Alembic commands ###
