"""rename tournament details

Revision ID: 5a5e7e2aa84f
Revises: 2dd38761d245
Create Date: 2025-02-12 23:29:24.526904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a5e7e2aa84f'
down_revision: Union[str, None] = '2dd38761d245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('additional_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('tournaments', 'tournament_details')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('tournament_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('tournaments', 'additional_details')
    # ### end Alembic commands ###
