"""Remove used patch columns

Revision ID: 5b4297d7f974
Revises: db637245a08b
Create Date: 2024-07-28 04:24:55.739429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b4297d7f974'
down_revision: Union[str, None] = 'db637245a08b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'game_version_major')
    op.drop_column('games', 'game_version_minor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('game_version_minor', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('games', sa.Column('game_version_major', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
