"""Add additional indexes to tables

Revision ID: 5db8f76d5748
Revises: 0933cdf8c8f7
Create Date: 2025-07-04 13:34:51.111608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5db8f76d5748'
down_revision: Union[str, None] = '0933cdf8c8f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_draft_events_game_champion_pick', 'draft_events', ['game_id', 'champion_id', 'is_pick'], unique=False)
    op.create_index('idx_games_type_version', 'games', ['game_type', 'game_version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_games_type_version', table_name='games')
    op.drop_index('idx_draft_events_game_champion_pick', table_name='draft_events')
    # ### end Alembic commands ###
