"""fix: rename tournament_game_number to series_game_number

Revision ID: 5fce8df8e0f1
Revises: 35a16fbfb2c7
Create Date: 2025-02-28 22:40:41.381939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fce8df8e0f1'
down_revision: Union[str, None] = '35a16fbfb2c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('series_game_number', sa.Integer(), nullable=True))
    op.drop_column('games', 'tournament_game_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('tournament_game_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('games', 'series_game_number')
    # ### end Alembic commands ###
