"""Additional information to a jsonb

Revision ID: 684bf43a08c4
Revises: 8e791c9f409a
Create Date: 2025-02-12 21:32:19.632634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '684bf43a08c4'
down_revision: Union[str, None] = '8e791c9f409a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('additional_information', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('teams', 'logo_url')
    op.drop_column('teams', 'colour_secondary')
    op.drop_column('teams', 'colour_primary')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('colour_primary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('teams', sa.Column('colour_secondary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('teams', sa.Column('logo_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('teams', 'additional_information')
    # ### end Alembic commands ###
