"""Refactors tournament table

Revision ID: 6ed6e95ec547
Revises: 56c95923a0d4
Create Date: 2024-10-05 19:53:25.849859

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ed6e95ec547"
down_revision: Union[str, None] = "56c95923a0d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # op.drop_table("tournaments")
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column("tournaments", sa.Column("id", sa.Integer(), autoincrement=True)
    op.add_column("games", sa.Column("tournament_id", sa.Integer(), nullable=True))
    op.add_column(
        "tournaments", sa.Column("name", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "tournaments", sa.Column("shortened_name", sa.String(length=30), nullable=True)
    )
    op.add_column("tournaments", sa.Column("start_date", sa.DateTime(), nullable=True))
    op.add_column("tournaments", sa.Column("end_date", sa.DateTime(), nullable=True))
    # op.add_column(
    #     "tournaments",
    #     "year",
    #     existing_type=sa.INTEGER(),
    #     type_=sa.SmallInteger(),
    #     nullable=True,
    # )
    # op.drop_column("tournaments", "playoffs")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # DO NOT RUN DOWNGRADE
    # ### end Alembic commands ###
