"""feat! Updates the columns stored in draft_events

Revision ID: 7c63f7c2aa33
Revises: 66a39b23f034
Create Date: 2025-02-28 22:14:28.284816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c63f7c2aa33'
down_revision: Union[str, None] = '66a39b23f034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft_events', sa.Column('champion', sa.Integer(), nullable=False))
    op.add_column('draft_events', sa.Column('participant_id', sa.Integer(), nullable=True))
    op.add_column('draft_events', sa.Column('updated', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'draft_events', 'champions', ['champion'], ['id'])
    op.drop_column('draft_events', 'champion_id')
    op.add_column('game_events', sa.Column('updated', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_events', 'updated')
    op.add_column('draft_events', sa.Column('champion_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'draft_events', type_='foreignkey')
    op.drop_column('draft_events', 'updated')
    op.drop_column('draft_events', 'participant_id')
    op.drop_column('draft_events', 'champion')
    # ### end Alembic commands ###
