"""Update indexes

Revision ID: 9588c44b79c5
Revises: e633fcc9f562
Create Date: 2025-05-03 15:14:18.671039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9588c44b79c5'
down_revision: Union[str, None] = 'e633fcc9f562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_participants_puuid_queue', 'participants', ['puuid'], unique=False, postgresql_include=['game_id'])
    op.create_index('idx_participants_puuid', 'participants', ['puuid'], unique=False)
    op.create_index('idx_participants_game_id', 'participants', ['game_id'], unique=False)
    op.create_index('idx_games_queue_id', 'games', ['queue_id'], unique=False)
    op.create_index('idx_games_end_timestamp', 'games', [sa.literal_column('game_end_timestamp DESC')], unique=False)
    op.create_index('idx_game_queue_timestamp', 'games', ['queue_id', sa.literal_column('game_end_timestamp DESC')], unique=False)
    op.create_index('idx_game_events_schema', 'game_events', ['schema'], unique=False)
    op.create_index('idx_game_events_game_id_schema_time', 'game_events', ['game_id', 'schema', 'game_time'], unique=False)
    op.create_index('idx_game_events_game_id_schema_seq', 'game_events', ['game_id', 'schema', 'sequence_index'], unique=False)
    op.create_index('idx_game_events_game_id_schema', 'game_events', ['game_id', 'schema'], unique=False)
    op.create_index('idx_game_events_game_id_game_time', 'game_events', ['game_id', 'game_time'], unique=False)
    op.create_index('idx_game_events_game_id', 'game_events', ['game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_game_events_game_id', table_name='game_events')
    op.drop_index('idx_game_events_game_id_game_time', table_name='game_events')
    op.drop_index('idx_game_events_game_id_schema', table_name='game_events')
    op.drop_index('idx_game_events_game_id_schema_seq', table_name='game_events')
    op.drop_index('idx_game_events_game_id_schema_time', table_name='game_events')
    op.drop_index('idx_game_events_schema', table_name='game_events')
    op.drop_index('idx_game_queue_timestamp', table_name='games')
    op.drop_index('idx_games_end_timestamp', table_name='games')
    op.drop_index('idx_games_queue_id', table_name='games')
    op.drop_index('idx_participants_game_id', table_name='participants')
    op.drop_index('idx_participants_puuid', table_name='participants')
    op.drop_index('idx_participants_puuid_queue', table_name='participants', postgresql_include=['game_id'])
    # ### end Alembic commands ###
