"""Remove tournament fk from game model

Revision ID: 9a8976c707f9
Revises: f191435b8782
Create Date: 2025-05-29 21:59:53.830644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a8976c707f9'
down_revision: Union[str, None] = 'f191435b8782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('games_tournament_id_fkey', 'games', type_='foreignkey')
    op.drop_column('games', 'tournament_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('tournament_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('games_tournament_id_fkey', 'games', 'tournaments', ['tournament_id'], ['id'])
    # ### end Alembic commands ###
