"""add external_ids column to tournament table

Revision ID: 9f75c52e8471
Revises: 5a5e7e2aa84f
Create Date: 2025-02-12 23:43:56.532504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f75c52e8471'
down_revision: Union[str, None] = '5a5e7e2aa84f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('external_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'external_ids')
    # ### end Alembic commands ###
