"""team_code nullable

Revision ID: b19e1e87a27b
Revises: 684bf43a08c4
Create Date: 2025-02-12 21:44:57.233764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b19e1e87a27b'
down_revision: Union[str, None] = '684bf43a08c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'team_code',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'team_code',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
