"""Add new participant stat table and remove surrender fields from game

Revision ID: b63e2b25866f
Revises: 0d07646761ed
Create Date: 2025-05-04 18:43:49.157129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b63e2b25866f'
down_revision: Union[str, None] = '0d07646761ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant_stats',
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('total_minions_killed', sa.Integer(), nullable=False),
    sa.Column('neutral_minions_killed', sa.Integer(), nullable=False),
    sa.Column('item_0', sa.Integer(), nullable=False),
    sa.Column('item_1', sa.Integer(), nullable=False),
    sa.Column('item_2', sa.Integer(), nullable=False),
    sa.Column('item_3', sa.Integer(), nullable=False),
    sa.Column('item_4', sa.Integer(), nullable=False),
    sa.Column('item_5', sa.Integer(), nullable=False),
    sa.Column('item_6', sa.Integer(), nullable=False),
    sa.Column('summoner_1_id', sa.Integer(), nullable=False),
    sa.Column('summoner_2_id', sa.Integer(), nullable=False),
    sa.Column('source_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_id')
    )
    op.drop_column('participants', 'game_ended_in_surrender')
    op.drop_column('participants', 'game_ended_in_early_surrender')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('game_ended_in_early_surrender', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('participants', sa.Column('game_ended_in_surrender', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table('participant_stats')
    # ### end Alembic commands ###
