"""Updates tournament table column types and adds correct associations

Revision ID: b90b0154f05c
Revises: 6ed6e95ec547
Create Date: 2024-10-05 20:20:22.092608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b90b0154f05c'
down_revision: Union[str, None] = '6ed6e95ec547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'games', 'tournaments', ['tournament_id'], ['id'])
    op.alter_column('tournaments', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               nullable=True)
    op.drop_column('tournaments', 'playoffs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('playoffs', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('tournaments', 'year',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'games', type_='foreignkey')
    # ### end Alembic commands ###
