"""Restore win to participant table

Revision ID: c1a1d5ae388e
Revises: 1a7cdbcd4176
Create Date: 2025-05-06 20:43:59.061838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a1d5ae388e'
down_revision: Union[str, None] = '1a7cdbcd4176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('win', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'win')
    # ### end Alembic commands ###
