"""feat! All InfoDTO columns should be nullable

Revision ID: c3e303128e9a
Revises: 5fce8df8e0f1
Create Date: 2025-03-02 00:24:09.460048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3e303128e9a'
down_revision: Union[str, None] = '5fce8df8e0f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'end_of_game_result',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('games', 'game_creation',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('games', 'game_duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('games', 'game_end_timestamp',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('games', 'game_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('games', 'game_mode',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('games', 'game_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('games', 'game_start_timestamp',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('games', 'game_type',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('games', 'game_version',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('games', 'map_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('games', 'platform_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('games', 'queue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('games', 'tournament_code',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'tournament_code',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('games', 'queue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('games', 'platform_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('games', 'map_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('games', 'game_version',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('games', 'game_type',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('games', 'game_start_timestamp',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('games', 'game_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('games', 'game_mode',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('games', 'game_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('games', 'game_end_timestamp',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('games', 'game_duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('games', 'game_creation',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('games', 'end_of_game_result',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
