"""Splits Game patch into major/minor

Revision ID: c928c5a9af04
Revises: 
Create Date: 2024-07-13 01:03:38.513080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c928c5a9af04'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('game_version_major', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('game_version_minor', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'game_version_minor')
    op.drop_column('games', 'game_version_major')
    # ### end Alembic commands ###
