"""Updates participant typing

Revision ID: d35cbd5d03c0
Revises: 32bf671416c3
Create Date: 2024-07-27 22:46:25.177642

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d35cbd5d03c0"
down_revision: Union[str, None] = "32bf671416c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "participants", "game_id", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "participants", "puuid", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "participants", "side", existing_type=sa.VARCHAR(length=10), nullable=False
    )
    op.alter_column("participants", "win", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "participants", "champion", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "participants", "champion_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "participants", "champion_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "participants", "champion", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column("participants", "win", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "participants", "side", existing_type=sa.VARCHAR(length=10), nullable=True
    )
    op.alter_column(
        "participants", "puuid", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "participants", "game_id", existing_type=sa.VARCHAR(length=255), nullable=True
    )
