"""merge game_participant with participant

Revision ID: d410813554f6
Revises: 04092ec444b2
Create Date: 2025-03-30 17:15:36.725191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd410813554f6'
down_revision: Union[str, None] = '04092ec444b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participants', 'win',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('participants', 'assists',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('participants', 'deaths',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('participants', 'game_ended_in_early_surrender',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('participants', 'game_ended_in_surrender',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('participants', 'kills',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('participants', 'summoner_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('participants', 'summoner_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('participants', 'team_position',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('participants', 'total_minions_killed',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('participants', 'neutral_minions_killed',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'participants', 'champions', ['champion_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participants', type_='foreignkey')
    op.alter_column('participants', 'neutral_minions_killed',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('participants', 'total_minions_killed',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('participants', 'team_position',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('participants', 'summoner_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('participants', 'summoner_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('participants', 'kills',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('participants', 'game_ended_in_surrender',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('participants', 'game_ended_in_early_surrender',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('participants', 'deaths',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('participants', 'assists',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
