"""removes unique constraint on team name

Revision ID: e177d8916aec
Revises: 5a4de713538e
Create Date: 2025-02-12 22:01:13.908496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e177d8916aec'
down_revision: Union[str, None] = '5a4de713538e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teams_name_key', 'teams', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('teams_name_key', 'teams', ['name'])
    # ### end Alembic commands ###
