"""Add win column to game participant

Revision ID: ec4c0b65e4c2
Revises: 0d0b2d97958d
Create Date: 2025-03-04 00:43:17.224975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec4c0b65e4c2'
down_revision: Union[str, None] = '0d0b2d97958d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_participants', sa.Column('win', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_participants', 'win')
    # ### end Alembic commands ###
